server:
  port: 8080
  context-path: /open-tracing-example
  
debug: false

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://postgres:5432/spring_boot_rest
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
