server:
  port: 8080
  servlet:
    contextPath: /open-tracing-example
  
debug: false

spring:
  application:
    name: open-tracing-example  
  jpa:
    properties:
       hibernate:
          jdbc:
             lob:
                non_contextual_creation: true  
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_boot_rest
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

opentracing:
  jaeger:
    udp-sender:
      host: localhost
      port: 6831    
          