version: "3.3"
services:
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "5778:5778"
      - "16686:16686"
    networks:
      - simulation

  open-tracing-example:
    container_name: open-tracing-example
    image: docker.io/paawak/open-tracing-example:latest
    depends_on:
      - jaeger
    ports:
      - "8080:8080"
      - "9999:9999"
    volumes:
      - "/kaaj/source/spring-boot-demo/open-tracing-example/target/jfr:/usr/local/logs/jfr"
    networks:
    - simulation

networks:
  simulation:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv4: "true"

