version: '2'

services:
    messaging-demo:
        image: paawak/messaging-demo:latest
        ports:
          - "8080:8080"
        environment:
          - spring.profiles.active=default,rabbitmq
        networks:
            - paawak-net
            
    rabbitmq:
        image: rabbitmq:3.7.6
        ports:
          - "5673:5672"        
        environment:
          - RABBITMQ_DEFAULT_USER=admin
          - RABBITMQ_DEFAULT_PASS=admin123
        networks:
            - paawak-net            

networks:
    paawak-net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.238.0/24


