spring:
  datasource:
    url: jdbc:h2:mem:bank_details
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      path: /h2
      enabled: true    
      settings:
        webAllowOthers: true
        trace: false

