server:
  port: 8080
  servlet:
    contextPath: /
    
app:
  config:
    message:
      queue: 
        bank-data: bank-data-queue    
  
logging:
  level:
    root: INFO
    com.swayam.demo: DEBUG
    org.springframework.web: INFO

spring:
  flyway:
    locations: classpath:/sql


