server:
  port: 9090
  servlet:
    contextPath: /
  
logging:
  level:
    root: INFO
    com.swayam.demo: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO

grpc:
   server:
      host: localhost
      port: 50051
          